apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: {{ .Values.deployment.api.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: host
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: database