apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
data:
    user: {{ .Values.secret.mysql.user | b64enc }}
    password: {{ .Values.secret.mysql.password | b64enc }}
    database: {{ .Values.secret.mysql.database | b64enc }}
    