deployment:
  frontend:
    image: placeholder
  api:
    image: placeholder

secret:
  mysql:
    user: placeholder
    password: placeholder
    database: placerholder

config:
  mysql:
    host: placeholder